services:
  devcross:
    build:
      context: .
      dockerfile: apps/devcross/Dockerfile
      target: development
    command: pnpm run start:dev devcross
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
